Mid section
Busiwa24/Test-Portfolio pull request #3
Opened 2021-07-15 20:27 UTC by Busiwa24

In the following pull request I have done the following:

-added the projects section
-frameworks section
-linter error checks
-added my about section
-I used the correct GitHub Flow:
- README file is descriptive.
- commit messages are meaningful.

2021-07-15 20:50 UTC, Emmyn5600 requested changes
## STATUS: Changes Requested :recycle:

Hi @Busiwa24 

Good job so far!:clap::clap:
You have done well in implementing the project requirements :clap:, However, there are some issues that you still need to work on to go to the next project but you are almost there!:muscle:

May I highlight the following:
- The repo looks professional:heavy_check_mark:
- Commit messages are good and descriptive:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have a descriptive PR:heavy_check_mark:
- Your Live demo link is working properly.:heavy_check_mark:


##  Required Changes:writing_hand:

**_Check the comments under the review._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-15 20:50 UTC, Emmyn5600 commented on style.css
> +.background-color {
- [ ] Nice work to use grid as required. Kindly, change this class name with a descriptive name. Imagine calling `background-color class` with background-color property.

2021-07-15 20:50 UTC, Emmyn5600 commented on index.html
> +        <span>See This Project</span>
- [ ] The button (e.g., "See This project") is a link a or button tag, and follow the button styling: Active, Hover and Pressed (see design), kindly make see this project as a link or button with a hover color.

2021-07-15 20:50 UTC, Emmyn5600 commented on index.html
> +        <span><ion-icon name="arrow-forward-outline"></ion-icon></span>
- [ ] The button (e.g., "See This project") is a link a or button tag, and follow the button styling: Active, Hover and Pressed (see design), kindly make see this project as a link or button with a hover color.

2021-07-15 20:50 UTC, Emmyn5600 commented on index.html
> +        <span><ion-icon name="arrow-forward-outline"></ion-icon></span>
- [ ] The button (e.g., "See This project") is a link a or button tag, and follow the button styling: Active, Hover and Pressed (see design), kindly make see this project as a link or button with a hover color.

2021-07-15 20:50 UTC, Emmyn5600 commented on index.html
> +        <span>See This Project</span>
- [ ] The button (e.g., "See This project") is a link a or button tag, and follow the button styling: Active, Hover and Pressed (see design), kindly make see this project as a link or button with a hover color.

2021-07-15 20:50 UTC, Emmyn5600 commented on index.html
> +        <span><ion-icon name="arrow-forward-outline"></ion-icon></span>
- [ ] The button (e.g., "See This project") is a link a or button tag, and follow the button styling: Active, Hover and Pressed (see design), kindly make see this project as a link or button with a hover color.

2021-07-15 20:50 UTC, Emmyn5600 commented on index.html
> +        <span><ion-icon name="download-outline"></ion-icon></span>
- [ ] The button (e.g., "Get My CV") is a link a or button tag, and follow the button styling: Active, Hover and Pressed (see design), kindly make see this project as a link or button with a hover color and pressed.

2021-07-16 09:17 UTC, Busiwa24 commented
Thank you for the feedback, I have implemented the required changes. 
-first I have changed the class name from background-color to project-card-background making it more descriptive
-second I have implemented hover and pressed effects on the buttons
You can have a look😊

2021-07-16 09:46 UTC, merged